services:

  bot:
    container_name: SurenTubeProxy
    image: ram3a9670/surentubeproxy:latest
    volumes:
      - .:/app
    command: make bot
    ports:
      - "2080:2080"
      - "2081:2081"
    networks:
      - default

networks:
  default:
    name: default_service
    external: true
